default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: 
  pool: 5

development:
  <<: *default
  database: myblog_development

test:
  <<: *default
  database: myblog_test

production:
  <<: *default
  database: myblog_production
  username: myblog
  password: <%= ENV['MYBLOG_DATABASE_PASSWORD'] %>
